CREATE TABLE "books"
(
    id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    isbn   VARCHAR(20)  NOT NULL UNIQUE,
    title  VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);

CREATE TABLE "copies"
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    isbn     VARCHAR(20)  NOT NULL,
    location VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_copies_books FOREIGN KEY (isbn) REFERENCES "books" (isbn)
);
